server:
  port: 8086

spring:
  application:
    name: stats-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/routeit?currentSchema=stats_schema}
    username: ${SPRING_DATASOURCE_USERNAME:routeit}
    password: ${SPRING_DATASOURCE_PASSWORD:routeit}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: stats_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    schemas: stats_schema
    locations: classpath:db/migration
  cache:
    type: simple

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info
